### ISSUE TITLE
video start time

### ISSUE THREAD

**Issue by dougsillars** [apivideo/player-sdk#10]
If I begin a video at time 15, for example:

http://embed.api.video/vod/vi4blUQJFrYWbaG44NChkH27#t=15

The player sends a "play" event to the analytics, but at t=0.

Expected:
 "play" at time 15
 
 OR
 "play' at time 0
 "seek.forward 0 to 15

**Comment by olivierapivideo** [comment]
Hi Doug,
This issue is not releated to the player SDK but to the player itself. This issue is not related to the player SDK but to the player itself. We added it to our TODO and will fix it soon. I'll let you know once it's done.

**Comment by olivierapivideo** [comment]
This as been fixed by the release 1.0.4 of the player.
