### ISSUE TITLE
Having issue while trying to import via webpack

### ISSUE THREAD

**Issue by peacepostman** [apivideo/player-sdk#14]
Hello,

I'm struggling while trying to import apivideo player with webpack. My code looks like this:

```
import(/* webpackChunkName: "ApiVideoPlayer" */ '@api.video/player-sdk').then(({ default: ApiVideoPlayer }) => {
   const PlayerSDK = ApiVideoPlayer.PlayerSdk;
// error ApiVideoPlayer return undefined
});
```

I guess it is related with your webpack configuration not using `libraryExport: 'default',` but you may have your reasons. Maybe you have a clue about how to make it work like this.

Best regards,

**Comment by olivierapivideo** [comment]
Hello, 

You're right, the library target isn't defined on 'default'.

You can make your code works using the following:

```javascript
import(/* webpackChunkName: "ApiVideoPlayer" */ '@api.video/player-sdk').then(({PlayerSdk}) => {
    const sdk = new PlayerSdk("#target", {
        // ...
    });
 });
```

Tell us if it solves your issue.

Best regards

**Comment by olivierapivideo** [comment]
I'm closing this issue since its looks that your problem is fixed. Feel free to re-open it if it's not the case.
