### ISSUE TITLE
Support for DOM events on the player

### ISSUE THREAD

**Issue by MiroDojkic** [apivideo/player-sdk#17]
Since the player is an `iframe`, it might be useful to enable listening to the native DOM events such as click and focus to avoid the iframe focus detection workarounds.
For example, one such use case could be if the developer wants to expose additional controls somewhere within the app once the video is focused.

I'm suggesting this assuming it would be easy to do in the same manner that the other events are exposed from the iframe (using the  `Window.postMessage()` method).
Thoughts?

**Comment by olivierapivideo** [comment]
Hi Miro,
Sorry for the delay. 
This is indeed an interesting idea. What are the events that you would like to see transmitted?

**Comment by MiroDojkic** [comment]
@olivierapivideo no problem, thanks for taking time to address this! 😊 

`focus` and `focusout` would serve our purpose well, as described in the use-case above.

**Comment by olivierapivideo** [comment]
Hi Miro, 
The version 1.2.6 is released, you can now listen to the following events: `useractive`, `userinactive`, `mouseenter`, and `mouseleave`.

Please let me know if it's ok for you.
