### ISSUE TITLE
Video quality / dimensions

### ISSUE THREAD

**Issue by luwes** [apivideo/player-sdk#18]
thanks for a great player API! 
I added api.video to my player benchmark over at https://dev.playerx.io/demo/api.video/

one thing that would be a nice addition is to have an idea what quality or video dimension is playing. is there a way to retrieve that information? 

the native html5 video element has a `resize` event that fires and the `.videoWidth` and `.videoHeight` properties.

**Comment by olivierapivideo** [comment]
Hello!
Thank you for your message. 
We plan to send more events in the near future. We will make sure to include quality changes and resizes events. We'll keep you informed here when it's done :)

**Comment by olivierapivideo** [comment]
Hi, 
The version 1.2.6 is released, you can now do the following:
```javascript
player.addEventListener('qualitychange', (ev) => { 
  console.log(ev.resolution.width, ev.resolution.height);
});
```
Please let me know if it's ok for you.

**Comment by luwes** [comment]
thank you! works great. https://dev.playerx.io/demo/api.video/
