### ISSUE TITLE
Timeupdate event

### ISSUE THREAD

**Issue by ngiraud** [apivideo/player-sdk#19]
Hi, and thanks for your work!

Is there a way to have access to the current time during playing, maybe with the timeupdate event of the HTML5 video player?

Seen here : https://dev.playerx.io/demo/api.video/ working, but when I try : 

`player.addEventListener('timeupdate', () => {
      console.log('timeupdate event received')
  })`

nothing is displayed

**Comment by olivierapivideo** [comment]
Hi Nicolas,

We will release a new version tomorrow that include this new feature.

**Comment by ngiraud** [comment]
Thanks !

**Comment by olivierapivideo** [comment]
Hi Nicolas, version 1.2.6 is released, you can now do the following:
```javascript
player.addEventListener('timeupdate', (ev) => { 
      console.log(ev.currentTime);
});
```
Please let me know if it's ok for you.

**Comment by ngiraud** [comment]
Hi!
Works great for me, thanks!
