### ISSUE TITLE
Consider open sourcing the Player SDK

### ISSUE THREAD

**Issue by lutangar** [apivideo/player-sdk#4]
At the moment, the player SDK feel very akward to use, especially in modern Js frameworks.

For now I gave up using this library and I'll stick to the iframe version of the player for now that suits our basic needs. Well, in the end, I'm still using this library, but in an iframe, which I have no control over.

Here are the pros of open-sourcing this library :
- Can be published on npm and install as a normal project dependency
- Can be built and shipped with the Js bundle of the project
- Can be adapted to suit any Js environments (see my foot note on using this with React)
- Trust. I don't trust a minified Js library.
- The community can do many things for you -> reducing cost
- ... 

There are plenty of other reasons to do so, but I'll let you, other fellow developers do the rest.

As a foot note, here's my twisted take of using this SDK in React :
```
import { useCallback } from "react";

export default function Video({ id }) {
  const playerRef = useCallback((node) => {
    if (node !== null) {
      try {
        const myNode = document.getElementById(node.id);
        myNode.textContent = "";
        apiVideoSdk.create(`#${node.id}`, {
          id,
        });
      } catch (e) {
        console.log(
          "You must activate third party cookies."
        );
      }
    }
  }, []);

  return (
      <div id="player" ref={playerRef} />
  );
}
```

Feel free to contact me if you want to discuss this further.

**Comment by olivierapivideo** [comment]
Hi @lutangar :) 
The player sdk has been rewritten using Typescript and is now open source.

**Comment by lutangar** [comment]
Good to know! Couldn't find it though, could you add a link to the source?

**Comment by olivierapivideo** [comment]
@lutangar https://github.com/apivideo/player-sdk/blob/master/index.ts

**Comment by lutangar** [comment]
> @lutangar https://github.com/apivideo/player-sdk/blob/master/index.ts

Alright, great thanks :+1:
